# NEXCARE-5G Network Setup Script
# Automatically finds server IP and configures AI agents

Write-Host "═══════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "   NEXCARE-5G Network Configuration Tool" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# Function to get WiFi IP address
function Get-WiFiIP {
    $adapters = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' -and $_.Name -like '*Wi-Fi*' }
    
    foreach ($adapter in $adapters) {
        $ip = Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $adapter.ifIndex -ErrorAction SilentlyContinue
        if ($ip) {
            return $ip.IPAddress
        }
    }
    
    # Fallback: try any active adapter
    $activeAdapters = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' }
    foreach ($adapter in $activeAdapters) {
        $ip = Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $adapter.ifIndex -ErrorAction SilentlyContinue
        if ($ip -and $ip.IPAddress -notlike '169.254.*' -and $ip.IPAddress -ne '127.0.0.1') {
            return $ip.IPAddress
        }
    }
    
    return $null
}

# Detect server IP
Write-Host "[1/5] Detecting Server IP Address..." -ForegroundColor Yellow
$serverIP = Get-WiFiIP

if (-not $serverIP) {
    Write-Host "❌ Could not detect IP address!" -ForegroundColor Red
    Write-Host "   Please check that you're connected to WiFi/Mobile Hotspot" -ForegroundColor Red
    Write-Host ""
    Write-Host "To manually find your IP:" -ForegroundColor Yellow
    Write-Host "  ipconfig | findstr IPv4" -ForegroundColor White
    Write-Host ""
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host "✅ Server IP detected: $serverIP" -ForegroundColor Green
Write-Host ""

# Display server URLs
Write-Host "[2/5] Server Access URLs:" -ForegroundColor Yellow
Write-Host "   Dashboard:       http://${serverIP}:3000" -ForegroundColor White
Write-Host "   API Health:      http://${serverIP}:3000/api/health" -ForegroundColor White
Write-Host "   Room Monitoring: http://${serverIP}:3000/room-monitoring" -ForegroundColor White
Write-Host "   NeoCare:         http://${serverIP}:3000/neocare" -ForegroundColor White
Write-Host "   GeriCare:        http://${serverIP}:3000/gericare" -ForegroundColor White
Write-Host ""

# Ask user what to configure
Write-Host "[3/5] What do you want to configure?" -ForegroundColor Yellow
Write-Host "   1. This is the Central Server (start Next.js)" -ForegroundColor White
Write-Host "   2. This is an AI Agent Laptop (configure .env)" -ForegroundColor White
Write-Host "   3. Just show me the IP and URLs (I'll configure manually)" -ForegroundColor White
Write-Host ""
$choice = Read-Host "Enter choice (1/2/3)"

switch ($choice) {
    "1" {
        Write-Host ""
        Write-Host "[4/5] Configuring Central Server..." -ForegroundColor Yellow
        
        # Check if in correct directory
        if (-not (Test-Path "package.json")) {
            Write-Host "❌ Not in edge-server2 directory!" -ForegroundColor Red
            Write-Host "   Please run this script from: C:\Users\krishna\Music\NEXCARE-5G\edge-server2" -ForegroundColor Red
            Write-Host ""
            Read-Host "Press Enter to exit"
            exit 1
        }
        
        # Create .env.local if it doesn't exist
        if (-not (Test-Path ".env.local")) {
            Write-Host "Creating .env.local..." -ForegroundColor Yellow
            @"
# Auto-generated by setup-network.ps1
# Server IP: $serverIP

NEXT_PUBLIC_API_URL=http://$serverIP:3000
NEXT_PUBLIC_SIGNALING_SERVER_URL=http://$serverIP:3000
NEXT_PUBLIC_OFFLINE_MODE=true

# Database
DATABASE_URL=file:./data/edgecare.db
"@ | Out-File -FilePath ".env.local" -Encoding UTF8
            Write-Host "✅ Created .env.local" -ForegroundColor Green
        } else {
            Write-Host "⚠️  .env.local already exists, updating URLs..." -ForegroundColor Yellow
            $envContent = @"
# Auto-generated by setup-network.ps1
# Server IP: $serverIP
# Updated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

NEXT_PUBLIC_API_URL=http://$serverIP:3000
NEXT_PUBLIC_SIGNALING_SERVER_URL=http://$serverIP:3000
NEXT_PUBLIC_OFFLINE_MODE=true

# Database
DATABASE_URL=file:./data/edgecare.db
"@
            $envContent | Out-File -FilePath ".env.local" -Encoding UTF8
            Write-Host "✅ Updated .env.local" -ForegroundColor Green
        }
        
        # Check firewall
        Write-Host "Checking Windows Firewall..." -ForegroundColor Yellow
        $firewallRule = Get-NetFirewallRule -DisplayName "NEXCARE Server" -ErrorAction SilentlyContinue
        
        if (-not $firewallRule) {
            Write-Host "⚠️  Firewall rule not found!" -ForegroundColor Yellow
            Write-Host "   Other laptops may not be able to connect." -ForegroundColor Yellow
            Write-Host ""
            $addFirewall = Read-Host "Add firewall rule? (requires admin) [Y/n]"
            
            if ($addFirewall -eq "" -or $addFirewall -eq "Y" -or $addFirewall -eq "y") {
                try {
                    New-NetFirewallRule -DisplayName "NEXCARE Server" `
                                       -Direction Inbound `
                                       -LocalPort 3000 `
                                       -Protocol TCP `
                                       -Action Allow `
                                       -ErrorAction Stop | Out-Null
                    Write-Host "✅ Firewall rule added!" -ForegroundColor Green
                } catch {
                    Write-Host "❌ Failed to add firewall rule (need admin privileges)" -ForegroundColor Red
                    Write-Host "   Run PowerShell as Administrator and use:" -ForegroundColor Yellow
                    Write-Host "   New-NetFirewallRule -DisplayName 'NEXCARE Server' -Direction Inbound -LocalPort 3000 -Protocol TCP -Action Allow" -ForegroundColor White
                }
            }
        } else {
            Write-Host "✅ Firewall rule already exists" -ForegroundColor Green
        }
        
        Write-Host ""
        Write-Host "[5/5] Ready to Start Server!" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "═══════════════════════════════════════════════════" -ForegroundColor Cyan
        Write-Host "   Server will be accessible at:" -ForegroundColor Cyan
        Write-Host "   http://${serverIP}:3000" -ForegroundColor Green
        Write-Host ""
        Write-Host "   Share this IP with other laptops:" -ForegroundColor Cyan
        Write-Host "   ${serverIP}" -ForegroundColor Green
        Write-Host "═══════════════════════════════════════════════════" -ForegroundColor Cyan
        Write-Host ""
        
        # Save IP to file for easy reference
        $serverIP | Out-File -FilePath "SERVER_IP.txt" -Encoding UTF8
        Write-Host "💾 Server IP saved to SERVER_IP.txt" -ForegroundColor Green
        Write-Host ""
        
        $startNow = Read-Host "Start the server now? [Y/n]"
        
        if ($startNow -eq "" -or $startNow -eq "Y" -or $startNow -eq "y") {
            Write-Host ""
            Write-Host "Starting server..." -ForegroundColor Green
            Write-Host "Press Ctrl+C to stop the server" -ForegroundColor Yellow
            Write-Host ""
            npm run dev
        } else {
            Write-Host ""
            Write-Host "To start the server manually, run:" -ForegroundColor Yellow
            Write-Host "  npm run dev" -ForegroundColor White
            Write-Host ""
        }
    }
    
    "2" {
        Write-Host ""
        Write-Host "[4/5] Configuring AI Agent..." -ForegroundColor Yellow
        Write-Host ""
        
        # Prompt for server IP (in case this laptop needs to connect to a different server)
        $useDetectedIP = Read-Host "Connect to detected server IP ($serverIP)? [Y/n]"
        
        if ($useDetectedIP -eq "n" -or $useDetectedIP -eq "N") {
            $serverIP = Read-Host "Enter Central Server IP address"
        }
        
        # Test connection to server
        Write-Host "Testing connection to server..." -ForegroundColor Yellow
        try {
            $response = Invoke-WebRequest -Uri "http://$serverIP:3000/api/health" -TimeoutSec 5 -UseBasicParsing -ErrorAction Stop
            Write-Host "✅ Server is reachable!" -ForegroundColor Green
        } catch {
            Write-Host "❌ Cannot reach server at http://$serverIP:3000" -ForegroundColor Red
            Write-Host "   Make sure:" -ForegroundColor Yellow
            Write-Host "   1. Central server is running (npm run dev)" -ForegroundColor White
            Write-Host "   2. Both laptops are on the same network" -ForegroundColor White
            Write-Host "   3. Firewall allows port 3000" -ForegroundColor White
            Write-Host ""
            $continue = Read-Host "Continue anyway? [y/N]"
            if ($continue -ne "y" -and $continue -ne "Y") {
                exit 1
            }
        }
        
        Write-Host ""
        Write-Host "Which AI agent is this laptop running?" -ForegroundColor Yellow
        Write-Host "   1. NeoCare (Baby Monitoring)" -ForegroundColor White
        Write-Host "   2. GeriCare (Fall Detection)" -ForegroundColor White
        $agentChoice = Read-Host "Enter choice (1/2)"
        
        if ($agentChoice -eq "1") {
            $module = "NeoCare-AI"
            $defaultRoom = "R2"
            $defaultPatient = "P001"
        } elseif ($agentChoice -eq "2") {
            $module = "GeriCare-AI"
            $defaultRoom = "R5"
            $defaultPatient = "P002"
        } else {
            Write-Host "❌ Invalid choice" -ForegroundColor Red
            Read-Host "Press Enter to exit"
            exit 1
        }
        
        Write-Host ""
        $roomId = Read-Host "Enter Room ID [$defaultRoom]"
        if ($roomId -eq "") { $roomId = $defaultRoom }
        
        $patientId = Read-Host "Enter Patient ID [$defaultPatient]"
        if ($patientId -eq "") { $patientId = $defaultPatient }
        
        # Create .env file
        $aiAgentsPath = "ai_agents"
        if (-not (Test-Path $aiAgentsPath)) {
            Write-Host "❌ ai_agents directory not found!" -ForegroundColor Red
            Write-Host "   Please run this script from: C:\Users\krishna\Music\NEXCARE-5G\edge-server2" -ForegroundColor Red
            Write-Host ""
            Read-Host "Press Enter to exit"
            exit 1
        }
        
        $envContent = @"
# Auto-generated by setup-network.ps1
# Configuration for $module

EDGE_SERVER_URL=http://$serverIP:3000
ROOM_ID=$roomId
PATIENT_ID=$patientId
MODULE=$module
MODEL_PATH=yolov8n.pt

# Optional settings
CONFIDENCE_THRESHOLD=0.75
ALERT_THRESHOLD=3
CHECK_INTERVAL=2
LOG_LEVEL=INFO
"@
        
        $envPath = Join-Path $aiAgentsPath ".env"
        $envContent | Out-File -FilePath $envPath -Encoding UTF8
        
        Write-Host ""
        Write-Host "✅ Configuration saved to: ai_agents\.env" -ForegroundColor Green
        Write-Host ""
        Write-Host "[5/5] Configuration Summary:" -ForegroundColor Yellow
        Write-Host "   Server:     http://$serverIP:3000" -ForegroundColor White
        Write-Host "   Module:     $module" -ForegroundColor White
        Write-Host "   Room ID:    $roomId" -ForegroundColor White
        Write-Host "   Patient ID: $patientId" -ForegroundColor White
        Write-Host ""
        Write-Host "To start the AI agent:" -ForegroundColor Yellow
        Write-Host "   1. Activate environment:  .\.venv\Scripts\Activate.ps1" -ForegroundColor White
        Write-Host "   2. Navigate to agents:    cd ai_agents" -ForegroundColor White
        if ($agentChoice -eq "1") {
            Write-Host "   3. Run agent:             python neocare_agent.py" -ForegroundColor White
        } else {
            Write-Host "   3. Run agent:             python gericare_agent.py" -ForegroundColor White
        }
        Write-Host ""
        
        $runNow = Read-Host "Would you like to start the agent now? [Y/n]"
        
        if ($runNow -eq "" -or $runNow -eq "Y" -or $runNow -eq "y") {
            Write-Host ""
            Write-Host "Starting AI agent..." -ForegroundColor Green
            Write-Host ""
            
            # Check if venv exists
            if (-not (Test-Path ".venv\Scripts\Activate.ps1")) {
                Write-Host "⚠️  Virtual environment not found!" -ForegroundColor Yellow
                Write-Host "   Please create it first with: python -m venv .venv" -ForegroundColor White
                Write-Host ""
                Read-Host "Press Enter to exit"
                exit 1
            }
            
            # Activate venv and run agent
            & .\.venv\Scripts\Activate.ps1
            Set-Location ai_agents
            
            if ($agentChoice -eq "1") {
                python neocare_agent.py
            } else {
                python gericare_agent.py
            }
        }
    }
    
    "3" {
        Write-Host ""
        Write-Host "[4/5] Manual Configuration Info:" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "Server IP Address: $serverIP" -ForegroundColor Green
        Write-Host ""
        Write-Host "Update your .env files with:" -ForegroundColor Yellow
        Write-Host "EDGE_SERVER_URL=http://$serverIP:3000" -ForegroundColor White
        Write-Host ""
        Write-Host "[5/5] Done!" -ForegroundColor Yellow
        Write-Host ""
        Read-Host "Press Enter to exit"
    }
    
    default {
        Write-Host "❌ Invalid choice" -ForegroundColor Red
        Write-Host ""
        Read-Host "Press Enter to exit"
        exit 1
    }
}

Write-Host ""
Write-Host "═══════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "   Setup Complete!" -ForegroundColor Green
Write-Host "═══════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
